When compiling certain files, headers were inserted in the wrong place causing a compilation error
/var/folders/bk/2chn3fj11_12d3vvwx6npbsw0000gn/T/src-0-18809.m:1:1: error: expected identifier or '('
^